### ISSUE TITLE
Questions about inference. 

### ISSUE THREAD

**Issue by iamjoong9** [changhaonan/A3VLM#4]
Hello, 

Thank you for your excellent research!

I would like to run a real-world demo using your project, similar to the ones shown in [Real-World Demo](https://github.com/changhaonan/A3VLM?tab=readme-ov-file#demos-on-real-world)

1. To do this, can I just use the checkpoints from [A3VLM-Eval](https://huggingface.co/SiyuanH/A3VLM-Eval) and [A3VLM](https://huggingface.co/SiyuanH/A3VLM) as mentioned in the [Inference Instruction](https://github.com/changhaonan/A3VLM/tree/main/model#inference)? Or do I have to follow all the training procedures?

2. For the llama_path in model/accessory/scripts/a3vlm_infer.sh, should I use the path to the files downloaded from [llama2-13b](https://huggingface.co/meta-llama/Llama-2-13b/tree/main)?

3. I see that the eval_affordance_v2.py function is used for inference. Do I also need to provide values for "partnet_dataset_root", "partnet_dataset_root_depth", "partnet_dataset_root_8points", and "ds_collections"? If so, could you please explain in detail what values should be used for these parameters?

Thank you again for your wonderful research. I am relatively new to this field, so I would greatly appreciate it if you could provide a detailed explanation.

**Comment by changhaonan** [comment]
We will provide a new inference example this week.

**Comment by SiyuanHuang95** [comment]
@JoongKu-Lee Please check our newly updated version, the demo usage could be found in model/accessory/demo_data/xxx.json, the usage script could refer to the a3vlm_7B_infer_test.sh

**Comment by iamjoong9** [comment]
Thanks a lot!
