### ISSUE TITLE
How can I obtain the 3D coordinates of an arrow？

### ISSUE THREAD

**Issue by OliverStaie** [changhaonan/A3VLM#6]
Dear author, thank you for your outstanding open-source contribution.

In your description, you can mark the target object with 8 points in the image and use an arrow to indicate the sliding direction or axis.

I found in your code that the `get_bbox_3d_proj()` method is used to obtain the 3D coordinates of 8 points. May I ask how to obtain the 3D coordinates coordinates of the arrow?

Looking forward to your guidance.

**Comment by OliverStaie** [comment]
Is the 3D coordinate of the arrow related to the `get_ axis_3d()` and `get_ axis_proj()` methods?

**Comment by changhaonan** [comment]
Which file you are talking about? If you are talking about during generation `get_ axis_3d()` will return 3d axis, and `get_ axis_proj()` will return projected 3d axis.

**Comment by changhaonan** [comment]
Is your problem solved?

**Comment by OliverStaie** [comment]
Thank you for your reply!! I'm talking about `vqa_task_construction.py`. I have another question to ask.
In your paper, the axis is an arrow that has direction. If the `get_axis_3d()` method returns `[[x1, y1, z1], [x2, y2, z2]]`, which of these two points is the starting point and which is the ending point of the arrow?

**Comment by changhaonan** [comment]
The first one is start and second is end.
